@echo off
rem C:\Users\mgy0003\Documents\GitHub\Coursera\C4Everyone_ProgrammingFundamentals\Week1\fahrenheit2celsius\mexopts.bat
rem Generated by gnumex.m script in C:\users\mgy0003\desktop\trunk
rem gnumex version: 2.06
rem Compile and link options used for building MEX etc files with
rem the Mingw/Cygwin tools.  Options here are:
rem Gnumex, version 2.06                       
rem MinGW linking                              
rem Mex (*.dll) creation                       
rem Libraries regenerated now                  
rem Language: C / C++                          
rem Optimization level: -O3 (full optimization)
rem StorageVersion: 1.0
rem C++keyName: GNU C++
rem C++keyManufacturer: GNU
rem C++keyLanguage: C++
rem C++keyVersion:
rem C++keyFileName: GNUMEXOPTS.bat
rem Matlab version 9.11
rem
set GCCINSTALLDIR=C:\msys64\mingw64\bin
set MATLAB=C:\PROGRA~1\MATLAB
set GM_PERLPATH=C:\PROGRA~1\MATLAB\sys\perl\win32\bin\perl.exe
set GM_UTIL_PATH=C:\users\mgy0003\desktop\trunk
set PATH=C:\msys64\mingw64\bin;%PATH%
set PATH=%PATH%;C:\Cygwin\usr\local\gfortran\libexec\gcc\i686-pc-cygwin\4.3.0
set LIBRARY_PATH=C:\msys64\mingw64\lib
set G95_LIBRARY_PATH=C:\msys64\mingw64\lib
set MW_TARGET_ARCH=win64
rem
rem precompiled library directory and library files
set GM_QLIB_NAME=C:\Users\mgy0003\AppData\Roaming\MATHWO~1\MATLAB\R2021b\gnumex
rem
rem directory for .def-files
set GM_DEF_PATH=C:\Users\mgy0003\AppData\Roaming\MATHWO~1\MATLAB\R2021b\gnumex
rem
rem Type of file to compile (mex or engine)
set GM_MEXTYPE=mex
rem
rem Language for compilation
set GM_MEXLANG=c
rem
rem File for exporting mexFunction symbol
set GM_MEXDEF=C:\Users\mgy0003\AppData\Roaming\MATHWO~1\MATLAB\R2021b\gnumex\mex.def
rem
set GM_ADD_LIBS=-llibmx -llibmex -llibmat
rem
rem compiler options; add compiler flags to compflags as desired
set NAME_OBJECT=-o
set COMPILER=gcc
set COMPFLAGS=-c -DMATLAB_MEX_FILE 
set OPTIMFLAGS=-O3
set DEBUGFLAGS=-g
set CPPCOMPFLAGS=%COMPFLAGS% -x c++ -fpermissive
set CPPOPTIMFLAGS=%OPTIMFLAGS%
set CPPDEBUGFLAGS=%DEBUGFLAGS%
rem
rem NB Library creation commands occur in linker scripts
rem but LIBLOC is provided for compatibility with
rem mex.getCompilerConfigurations
rem
rem Linker parameters
set LIBLOC=
set LINKER=%GM_PERLPATH% %GM_UTIL_PATH%\linkmex.pl
set LINKFLAGS=
set CPPLINKFLAGS=GM_ISCPP 
set LINKOPTIMFLAGS=-s
set LINKDEBUGFLAGS=-g  -Wl,--image-base,0x28000000\n
set LINKFLAGS= -LC:\Users\mgy0003\AppData\Roaming\MATHWO~1\MATLAB\R2021b\gnumex
set LINK_FILE=
set LINK_LIB=
set NAME_OUTPUT=-o %OUTDIR%%MEX_NAME%.mexw64
rem
rem Resource compiler parameters
set RC_COMPILER=%GM_PERLPATH% %GM_UTIL_PATH%\rccompile.pl  -o %OUTDIR%mexversion.res
set RC_LINKER=
